apiVersion: v1 # 使用 Kubernetes v1 API 版本
kind: PersistentVolumeClaim # 定义资源类型为 PersistentVolumeClaim (PVC)
metadata:
  name: database-persistent-volume-claim # PVC 的名称，用于唯一标识该声明
spec:
  accessModes:
    - ReadWriteOnce # PVC 的访问模式：允许单个节点以读写方式挂载该卷
  resources:
    requests:
      storage: 2Gi # 申请 2GB 的存储空间，这是容器需要的最小存储量
